[tool.poetry]
name = "scrap"
version = "0.1.0"
description = "Finding phishing sites"
authors = ["MATUMOTO"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
